### PR TITLE
Cleanedup-controller

### PR DESCRIPTION
**Pull request by sairamch04**

### CODE REVIEW

**Comment by SainathB** [comment]
Looks fine.

**Comment by SainathB** [comment]
You can delete it right?

**Comment by sairamch04** [comment]
Yep. We are not deleting. Just changed the package name and unnecessary imports

**Comment by SainathB** [comment]
We will eventually delete it and add new controllers.

**Comment by sairamch04** [comment]
Yes. But currently if we pull from master, We cannot immediately run it . So

**Pull request merged**
